services:
  nginx:
    image: nginx:1.27-bookworm-otel
    ports:
      - "${PUBLIC_PORT:-8080}:80"
    depends_on:
      app:
        condition: service_started
    environment:
      OTLP_ENDPOINT: "http://collector:4317"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ${PWD}/nginx/nginx.conf.template
        target: /etc/nginx/nginx.conf.template
      - type: bind
        source: ${PWD}/nginx/docker-entrypoint.sh
        target: /docker-entrypoint.sh
      - type: bind
        source: ${PWD}/nginx/conf.d
        target: /etc/nginx/conf.d
    entrypoint: /docker-entrypoint.sh
  app:
    image: otel-kotlin-api-usage-with-spring-starter
    environment:
      OTEL_SERVICE_NAME: "otel-kotlin-zero-code-instrumentation-practice"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.136.0@sha256:45392d534c1edcc809c2d112394029246bc679d2ae5ea7081414a1fc74f2c621
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
    command: ["--config=/config.yaml"]
    # expose:
    #   - "4317"
    # ports:
    #   - "4317:4317"
